#!/bin/bash
#
#  AppRun: TARSISETC's multitool launcher
#
#  Copyright (C) 2023 Gonzalo José Carracedo Carballal
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this program.  If not, see
#  <http://www.gnu.org/licenses/>
#

SELF=$(readlink -f "$0")
HERE=${SELF%/*}

ARGV0=`basename "$ARGV0"`

export TARSIS_ETC_DATA_DIR="${HERE}/../share/TARSIS/data"
export LD_LIBRARY_PATH="${HERE}/../lib:$LD_LIBRARY_PATH"

EXEC="${HERE}/CalGUI"
ARGS=

# Detect tool
case "$ARGV0" in
    calcli*)
	EXEC="${HERE}/Calculator"
	ARGS=
	;;
esac

# Launch tool
exec  -a "$ARGV0" "$EXEC" `echo $ARGS` "$@"
